AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'lbb

  Sample SAM Template for lbb

  '
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
Parameters:
  Environment:
    Type: String
    Default: dev
Resources:
  LBBApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: LLB Api Gateway
      StageName: Staging
  AuthenticationsFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: AuthenticationsFunctions
      Handler: authentication.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: LBBApiGateway
            Path: /auth_
            Method: GET
      Timeout: 3
      MemorySize: 128
      FunctionName:
        Fn::Sub: ${Environment}-authentications-test
      Environment:
        Variables:
          ConfigBucket:
            Fn::Sub: ${Environment}-authentications-test
      Policies:
      - AmazonS3FullAccess
      - AmazonAthenaFullAccess
    Metadata:
      SamResourceId: AuthenticationsFunctions
  ActionsFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ActionsFunctions
      Handler: action.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: LBBApiGateway
            Path: /action
            Method: GET
      Timeout: 3
      MemorySize: 128
      FunctionName:
        Fn::Sub: ${Environment}-actions-test
      Environment:
        Variables:
          ConfigBucket:
            Fn::Sub: ${Environment}-actions-test
      Policies:
      - AmazonS3FullAccess
      - AmazonAthenaFullAccess
    Metadata:
      SamResourceId: ActionsFunctions
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: lbb-table
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
